on: [push]

jobs:
  test:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v3
       - name: Set up Python
         uses: actions/setup-python@v3
       - name: Run tests
         run: |
          python3 -m pip install -r requirements.txt
          python3  main.py &
          python3 tests.py